# -*- coding: utf-8 -*-
"""jobcheck.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c605laVspCj3L6xKpfeb-EqxA2y4OTpc
"""

import pandas as pd
df=pd.read_csv("/content/fake_job_postings.csv", engine='python', on_bad_lines='skip')
df.head()


from ydata_profiling import ProfileReport

profile = ProfileReport(df, explorative=True)
profile.to_notebook_iframe()

df.drop(['job_id'], axis=1, inplace=True)

df.drop(['department'], axis=1, inplace=True)
df.drop(['salary_range'], axis=1, inplace=True)

df['benefits'] = df['benefits'].fillna('')

df['text'] = df['title'] + " " + df['description'] + " " + df['company_profile'] + " " + df['requirements'] + " " + df['benefits']

df.fillna('', inplace=True)

X = df['text']
y = df['fraudulent'].replace('', 0).astype(int)

from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(stop_words='english', max_features=10000,ngram_range=(1,2))

X = vectorizer.fit_transform(X)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from imblearn.over_sampling import SMOTE

smote = SMOTE()
X_train_sm, y_train_sm = smote.fit_resample(X_train, y_train)

"""Let's try an XGBoost classifier, which is often more robust and can handle imbalanced datasets more effectively than RandomForest. We will also use `scale_pos_weight` to help address the class imbalance directly within the model training."""

import xgboost as xgb
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Calculate the scale_pos_weight for handling imbalance
# It's (count of negative examples) / (count of positive examples)
scale_pos_weight_value = sum(y_train_sm == 0) / sum(y_train_sm == 1)

# Initialize and train XGBoost Classifier
xgb_model = xgb.XGBClassifier(
    objective='binary:logistic',
    eval_metric='logloss',
    use_label_encoder=False, # Suppress the warning
    random_state=42,
    scale_pos_weight=scale_pos_weight_value # Apply the weight
)

xgb_model.fit(X_train_sm, y_train_sm)

# Make predictions on the original (un-resampled) test set
y_pred_xgb = xgb_model.predict(X_test)

import matplotlib.pyplot as plt
import seaborn as sns

print("XGBoost Classifier with SMOTE")
print("Accuracy:", accuracy_score(y_test, y_pred_xgb))
print("\nClassification Report:")
print(classification_report(y_test, y_pred_xgb))

# Plot Confusion Matrix
cm_xgb = confusion_matrix(y_test, y_pred_xgb)
plt.figure(figsize=(8, 6))
sns.heatmap(cm_xgb, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Predicted Non-Fraudulent', 'Predicted Fraudulent'],
            yticklabels=['Actual Non-Fraudulent', 'Actual Fraudulent'])
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix - XGBoost Classifier with SMOTE')
plt.show()

"""### Adjusting Classification Threshold
Given the imbalance and the current model's high recall but low precision for fraudulent jobs, let's explore adjusting the classification threshold. By default, the threshold is 0.5. We can predict probabilities and then use a custom threshold to balance precision and recall for the minority class.
"""

from sklearn.metrics import precision_recall_curve, auc
import numpy as np

# Get probability predictions for the positive class (fraudulent)
y_pred_proba = xgb_model.predict_proba(X_test)[:, 1]

# Calculate precision and recall for various thresholds
precision, recall, thresholds = precision_recall_curve(y_test, y_pred_proba)

# Plot the Precision-Recall curve
plt.figure(figsize=(10, 7))
plt.plot(recall, precision, marker='.')
plt.xlabel('Recall')
plt.ylabel('Precision')
plt.title('Precision-Recall Curve for XGBoost Classifier')
plt.grid(True)
plt.show()

# Find the optimal threshold (e.g., where F1-score is maximized, or based on business needs)
# For demonstration, let's find a threshold that attempts to balance precision and recall
# This is often subjective, but we can look for a point where both are reasonably high

# Example: print precision, recall, and f1-score for a few thresholds
for i in range(0, len(thresholds), 10):
    thresh = thresholds[i]
    y_pred_tuned = (y_pred_proba >= thresh).astype(int)
    report = classification_report(y_test, y_pred_tuned, output_dict=True)
    f1_score = report['1']['f1-score']
    precision_score = report['1']['precision']
    recall_score = report['1']['recall']
    print(f"Threshold: {thresh:.4f} | Precision: {precision_score:.4f} | Recall: {recall_score:.4f} | F1-Score: {f1_score:.4f}")

print(f"Accuracy for the last tuned threshold: {accuracy_score(y_test, y_pred_tuned):.4f}")

from sklearn.metrics import f1_score

# Find the optimal threshold that maximizes F1-score for the positive class
f_scores = []
for p, r, t in zip(precision, recall, thresholds):
    # Calculate F1-score for the positive class (class 1)
    if (p + r) == 0:  # Avoid division by zero
        f_scores.append(0.0)
    else:
        f_scores.append(2 * (p * r) / (p + r))

optimal_idx = np.argmax(f_scores)
optimal_threshold = thresholds[optimal_idx]

print(f"Optimal Threshold (maximizing F1-score for fraudulent class): {optimal_threshold:.4f}")

# Apply the optimal threshold to make predictions
y_pred_optimal = (y_pred_proba >= optimal_threshold).astype(int)

print("\nClassification Report with Optimal Threshold:")
print(classification_report(y_test, y_pred_optimal))

# Plot Confusion Matrix with Optimal Threshold
cm_optimal = confusion_matrix(y_test, y_pred_optimal)
plt.figure(figsize=(8, 6))
sns.heatmap(cm_optimal, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Predicted Non-Fraudulent', 'Predicted Fraudulent'],
            yticklabels=['Actual Non-Fraudulent', 'Actual Fraudulent'])
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix - XGBoost with Optimal Threshold (F1-score)')
plt.show()

"""### Checking for Overfitting: Training Set Performance"""

# Make predictions on the SMOTE-resampled training set
y_pred_train = xgb_model.predict(X_train_sm)

print("XGBoost Classifier Training Set Classification Report:")
print(classification_report(y_train_sm, y_pred_train))

"""From the Precision-Recall curve and the printed scores, we can choose a threshold that better suits our goals. For example, if we want to reduce false positives (increase precision for class 1) even if it means missing some fraudulent jobs (decreasing recall for class 1), we would choose a higher threshold. Conversely, to find more fraudulent jobs, we'd use a lower threshold."""
